#!/usr/bin/env python3

"""
    Copyright © 2024 - 2025 MeshX
    Extended version with GPIO support
"""

import yaml
import os
import argparse
import sys

# Add the original code_gen.py directory to path to import it
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Try to import the original CodeGen class
try:
    from code_gen import CodeGen, CodeGenException, file_insert
except ImportError:
    # If import fails, define the base classes here
    file_insert =   "/****************************************************************************\n"\
                    " * MESHX AUTOGEN CODE \n"\
                    " * @brief This file is auto-generated by the meshx tool. \n"\
                    " *       Do not modify this file manually.\n"\
                    " *\n"\
                    " * @file meshx_config.h\n"\
                    " *\n"\
                    " ****************************************************************************/\n"\
                    "#ifndef __MESHX_AUTO_GEN__\n#define __MESHX_AUTO_GEN__\n"

    class CodeGenException(Exception):
        """
        Custom exception class for CodeGen.
        """
        pass

    class CodeGen:
        """
        Base CodeGen class for generating code from product and model profiles.
        """
        def __init__(self,
                     target_name,
                     meshx_root,
                     config_path="components/meshx/default/inc",
                     prod_profile="tools/scripts/prod_profile.yml",
                     model_profile="tools/scripts/model_profile.yml"
                ):
            """
            Initialize the CodeGen class with product and model profiles in YAML format.

            Args:
                target_name (str): Name of the target product.
                prod_profile (str): Path to the product profile YAML file.
                model_profile (str): Path to the model profile YAML file.
            """
            self.max_el = 1
            self.target = target_name
            self.meshx_root = meshx_root
            # Load product and model profiles from YAML files
            with open(prod_profile) as pj:
                self.prod_profile = yaml.safe_load(pj)
            with open(model_profile) as mj:
                self.prod_profile.update(yaml.safe_load(mj))
            self.product_list = []
            self.product = None
            self.pid = None
            self.cid = self.prod_profile['prod']['cid']
            self.c_list = []  # List of source files
            self.inc_list = []  # List of include directories
            self.deps = {}  # Dependency dictionary
            self.__find_prod_from_target()
            self.file_insert = file_insert
            self.genfile_h = config_path + "/meshx_config.h"
            self.define_fmt = "\n#define {}{}{}"
            if os.name == 'nt':
                os.system(f'echo.>{self.genfile_h}')  # Create the header file
            elif os.name =='posix':
                os.system(f'touch {self.genfile_h}')  # Create the header file

        def __str__(self):
            """
                Return the autogenerated code as a string.
            """
            return self.file_insert

        def __get_fmt_define(self, name, value):
            """
            Get the define format for the autogenerated code.
            """
            leng = 50 - len(name)
            return self.define_fmt.format(name, (" " * leng), value)

        def __find_prod_from_target(self):
            """
            Find the product from the target name.
            """
            self.product_list = self.prod_profile['prod']['products']
            for product in self.product_list:
                if product['name'] == self.target:
                    self.product = product
                    self.pid = self.product['pid']
            if self.product is None:
                raise CodeGenException("Product Not Found")

        def __get_src_from_path(self, path):
            """
            Get all source files from the given path.
            """
            if path is None:
                return
            path_walk = self.meshx_root + "/" + path
            for (root,dirs,files) in os.walk(path_walk):
                for file in files:
                    if file.endswith('.c'):  # Check if the file ends with .c
                        filepath = f"{root}/{file}"
                        if filepath not in self.c_list:
                            self.c_list.append(filepath)  # Add full path to list
                    if file.endswith('.h') and f"{root}" not in self.inc_list:
                        self.inc_list.append(root)

        def close(self):
            """
            Close the CodeGen class and write the autogenerated code to a header file.
            """
            self.get_all_macro()
            self.file_insert += "\n\n#endif /* __MESHX_AUTO_GEN__ */"
            with open(self.genfile_h, 'w') as genfile:
                genfile.write(str(self) + '\n')

        def get_common_defs(self):
            """
            Get common definitions from the product profile.
            """
            self.max_el = 1
            if self.product is not None:
                for element in self.product['elements']:
                    values = element.values()
                    for value in values:
                        self.max_el += value
            self.file_insert += self.__get_fmt_define("CONFIG_CID_ID", hex(self.cid))
            self.file_insert += self.__get_fmt_define("CONFIG_PID_ID", hex(self.pid))
            self.file_insert += self.__get_fmt_define("CONFIG_PRODUCT_NAME", f'"{self.target[:16:]}"')
            self.file_insert += self.__get_fmt_define("CONFIG_MAX_ELEMENT_COUNT", self.max_el)
            return self.file_insert

        def get_all_macro(self):
            """
            Get all macros from the product profile.
            """
            if self.product is not None:
                for _key in ['elements', 'models', 'base_models', 'components']:
                    if _key in self.prod_profile:
                        for __key in self.prod_profile[_key]:
                            if 'macros' in self.prod_profile[_key][__key]:
                                for macro in self.prod_profile[_key][__key]['macros']:
                                    self.file_insert += self.__get_fmt_define(macro['def'], int(macro['value']))

class CodeGenExtended(CodeGen):
    """
    Extended CodeGen class with GPIO support.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.gpio_pins = []
        self.gpio_config_valid = False

    def parse_gpio_config(self):
        """
        Parse GPIO configuration from product profile.
        """
        if self.product is None:
            return

        # Check if product has GPIO configuration
        if 'gpio' in self.product:
            gpio_config = self.product['gpio']

            # Validate GPIO configuration structure
            if 'pins' not in gpio_config:
                raise CodeGenException("GPIO configuration missing 'pins' section")

            pins = gpio_config['pins']
            if not isinstance(pins, list):
                raise CodeGenException("GPIO pins must be a list")

            # Parse each pin configuration
            for pin_idx, pin_config in enumerate(pins):
                self._validate_gpio_pin_config(pin_config, pin_idx)
                self.gpio_pins.append(pin_config)

            self.gpio_config_valid = True

    def _validate_gpio_pin_config(self, pin_config, pin_idx):
        """
        Validate a single GPIO pin configuration.

        Args:
            pin_config (dict): GPIO pin configuration
            pin_idx (int): Pin index for error reporting
        """
        required_fields = ['name', 'logical_pin', 'physical_pin', 'mode']
        for field in required_fields:
            if field not in pin_config:
                raise CodeGenException(f"GPIO pin {pin_idx} missing required field: {field}")

        # Validate logical pin range (0-255)
        logical_pin = pin_config['logical_pin']
        if not isinstance(logical_pin, int) or logical_pin < 0 or logical_pin > 255:
            raise CodeGenException(f"GPIO pin {pin_idx} has invalid logical_pin: {logical_pin}. Must be 0-255.")

        # Validate physical pin (platform-specific, but should be integer)
        physical_pin = pin_config['physical_pin']
        if not isinstance(physical_pin, int):
            raise CodeGenException(f"GPIO pin {pin_idx} has invalid physical_pin: {physical_pin}. Must be integer.")

        # Validate mode
        valid_modes = ['input', 'output', 'input_output', 'open_drain',
                      'open_drain_input_output', 'pwm_output']
        mode = pin_config['mode']
        if mode not in valid_modes:
            raise CodeGenException(f"GPIO pin {pin_idx} has invalid mode: {mode}. Valid modes: {valid_modes}")

        # Validate optional fields if present
        if 'pull' in pin_config:
            valid_pulls = ['none', 'pull_up', 'pull_down', 'pull_up_down']
            if pin_config['pull'] not in valid_pulls:
                raise CodeGenException(f"GPIO pin {pin_idx} has invalid pull: {pin_config['pull']}. Valid pulls: {valid_pulls}")

        if 'drive_strength' in pin_config:
            valid_drives = ['weak', 'medium', 'strong', 'max_strong']
            if pin_config['drive_strength'] not in valid_drives:
                raise CodeGenException(f"GPIO pin {pin_idx} has invalid drive_strength: {pin_config['drive_strength']}. Valid drives: {valid_drives}")

        if 'initial_level' in pin_config:
            level = pin_config['initial_level']
            if level not in [0, 1]:
                raise CodeGenException(f"GPIO pin {pin_idx} has invalid initial_level: {level}. Must be 0 or 1.")

        # Validate mode-specific configuration
        if mode == 'pwm_output':
            if 'pwm' not in pin_config:
                raise CodeGenException(f"GPIO pin {pin_idx} (PWM mode) missing 'pwm' configuration")

            pwm_config = pin_config['pwm']
            if 'frequency' not in pwm_config:
                raise CodeGenException(f"GPIO pin {pin_idx} (PWM mode) missing 'frequency'")
            if 'duty_cycle' not in pwm_config:
                raise CodeGenException(f"GPIO pin {pin_idx} (PWM mode) missing 'duty_cycle'")
            if 'resolution' not in pwm_config:
                raise CodeGenException(f"GPIO pin {pin_idx} (PWM mode) missing 'resolution'")

            # Validate PWM parameters
            if not isinstance(pwm_config['frequency'], int) or pwm_config['frequency'] <= 0:
                raise CodeGenException(f"GPIO pin {pin_idx} has invalid PWM frequency: {pwm_config['frequency']}. Must be positive integer.")

            duty_cycle = pwm_config['duty_cycle']
            if not isinstance(duty_cycle, int) or duty_cycle < 0 or duty_cycle > 100:
                raise CodeGenException(f"GPIO pin {pin_idx} has invalid PWM duty_cycle: {duty_cycle}. Must be 0-100.")

            resolution = pwm_config['resolution']
            if not isinstance(resolution, int) or resolution < 1 or resolution > 16:
                raise CodeGenException(f"GPIO pin {pin_idx} has invalid PWM resolution: {resolution}. Must be 1-16.")

        elif 'interrupt' in pin_config:
            intr_config = pin_config['interrupt']
            if 'trigger' not in intr_config:
                raise CodeGenException(f"GPIO pin {pin_idx} (interrupt) missing 'trigger'")

            valid_triggers = ['disabled', 'positive_edge', 'negative_edge',
                            'any_edge', 'low_level', 'high_level']
            if intr_config['trigger'] not in valid_triggers:
                raise CodeGenException(f"GPIO pin {pin_idx} has invalid interrupt trigger: {intr_config['trigger']}. Valid triggers: {valid_triggers}")

    def generate_gpio_macros(self):
        """
        Generate GPIO configuration macros for meshx_config.h
        """
        if not self.gpio_config_valid:
            return

        # Generate GPIO pin count macro
        pin_count = len(self.gpio_pins)
        self.file_insert += self.__get_fmt_define("CONFIG_GPIO_PIN_COUNT", pin_count)

        # Generate macros for each pin
        for pin_config in self.gpio_pins:
            name = pin_config['name']
            logical_pin = pin_config['logical_pin']
            physical_pin = pin_config['physical_pin']

            # Generate pin definition macros
            self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_LOGICAL", logical_pin)
            self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PHYSICAL", physical_pin)

            # Generate mode macro (convert string to integer)
            mode_map = {
                'input': 0,
                'output': 1,
                'input_output': 2,
                'open_drain': 3,
                'open_drain_input_output': 4,
                'pwm_output': 5
            }
            mode_value = mode_map.get(pin_config['mode'], 0)
            self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_MODE", mode_value)

            # Generate pull macro if specified
            if 'pull' in pin_config:
                pull_map = {
                    'none': 0,
                    'pull_up': 1,
                    'pull_down': 2,
                    'pull_up_down': 3
                }
                pull_value = pull_map.get(pin_config['pull'], 0)
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PULL", pull_value)

            # Generate drive strength macro if specified
            if 'drive_strength' in pin_config:
                drive_map = {
                    'weak': 0,
                    'medium': 1,
                    'strong': 2,
                    'max_strong': 3
                }
                drive_value = drive_map.get(pin_config['drive_strength'], 1)
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_DRIVE", drive_value)

            # Generate initial level macro if specified
            if 'initial_level' in pin_config:
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_INITIAL_LEVEL", pin_config['initial_level'])

            # Generate signal inversion macro if specified
            if 'signal_inversion' in pin_config:
                inv_value = 1 if pin_config['signal_inversion'] else 0
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_SIGNAL_INVERSION", inv_value)

            # Generate PWM macros if applicable
            if pin_config['mode'] == 'pwm_output' and 'pwm' in pin_config:
                pwm_config = pin_config['pwm']
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PWM_FREQUENCY", pwm_config['frequency'])
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PWM_DUTY_CYCLE", pwm_config['duty_cycle'])
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PWM_RESOLUTION", pwm_config['resolution'])
                if 'channel' in pwm_config:
                    self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PWM_CHANNEL", pwm_config['channel'])

            # Generate interrupt macros if applicable
            if 'interrupt' in pin_config:
                intr_config = pin_config['interrupt']
                trigger_map = {
                    'disabled': 0,
                    'positive_edge': 1,
                    'negative_edge': 2,
                    'any_edge': 3,
                    'low_level': 4,
                    'high_level': 5
                }
                trigger_value = trigger_map.get(intr_config['trigger'], 0)
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_INTR_TRIGGER", trigger_value)

                if 'task_priority' in intr_config:
                    self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_INTR_PRIORITY", intr_config['task_priority'])

                if 'task_stack_size' in intr_config:
                    self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_INTR_STACK_SIZE", intr_config['task_stack_size'])

    def generate_gpio_config_data(self):
        """
        Generate GPIO configuration data structures.
        This would typically generate a .c file with configuration data.
        For now, we'll just note that this needs to be implemented.
        """
        if not self.gpio_config_valid:
            return

        # Note: In a full implementation, this would generate:
        # 1. A C header with GPIO configuration structures
        # 2. A C source file with initialized configuration data
        # 3. Macros for accessing the configuration

        # For Task 1, we're just setting up the infrastructure.
        # The actual data structure generation will be in later tasks.
        pass

    def get_common_defs(self):
        """
        Override to include GPIO macros.
        """
        result = super().get_common_defs()

        # Parse and generate GPIO configuration
        try:
            self.parse_gpio_config()
            self.generate_gpio_macros()
            self.generate_gpio_config_data()
        except CodeGenException as e:
            print(f"Warning: GPIO configuration error: {e}")
            print("GPIO configuration will be skipped.")
        except Exception as e:
            print(f"Warning: Unexpected error processing GPIO configuration: {e}")
            print("GPIO configuration will be skipped.")

        return result

def main():
    """
    Main function for extended code generator.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('prod', type=str, help='Name of the target product')
    parser.add_argument('--root', type=str, default="components/meshx", help='Root directory path for MeshX')
    parser.add_argument('--config', type=str, default=".", help='directory to generate meshx_config.h')
    parser.add_argument('--profile', type=str, default="tools/scripts", help='directory to get product_profile.yml')

    args = parser.parse_args()

    # Create extended code generator
    gen = CodeGenExtended(args.prod, args.root, config_path=args.config, prod_profile=args.profile)

    # Generate common definitions (includes GPIO)
    gen.get_common_defs()

    # Note: The original code_gen.py has additional methods for resolving
    # dependencies. For Task 1, we're focusing on GPIO infrastructure.
    # These would be called in a full implementation.

    # Close and write the file
    gen.close()

    print(f">> Extended autogen code created with GPIO support! \n{gen}")

if __name__ == '__main__':
    main()
