#!/usr/bin/env python3

"""
    Copyright © 2024 - 2025 MeshX
"""

import yaml
import os
import argparse
import struct
import sys

# Add proto directory to path to import generated protobuf classes
PROTO_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'proto')
if PROTO_PATH not in sys.path:
    sys.path.append(PROTO_PATH)

try:
    import meshx_config_pb2
except ImportError as e:
    # If the file exists but import fails, it's likely a missing 'protobuf' package
    if os.path.exists(os.path.join(PROTO_PATH, 'meshx_config_pb2.py')):
        print(f"Error: Failed to import 'meshx_config_pb2'. Please ensure 'protobuf' python package is installed: {e}")
    else:
        print("Warning: meshx_config_pb2.py not found. Please compile the protobuf schema.")
    meshx_config_pb2 = None

def crc16_ccitt(data, crc=0xFFFF):
    """
    Calculate the CRC16-CCITT checksum for the given data.

    Args:
        data (bytes): Data to calculate the checksum for.
        crc (int): Initial CRC value.

    Returns:
        int: CRC16-CCITT checksum.
    """
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            if crc & 0x8000:
                crc = ((crc << 1) ^ 0x1021) & 0xFFFF
            else:
                crc = (crc << 1) & 0xFFFF
    return crc

parser = argparse.ArgumentParser()

parser.add_argument('prod', type=str, help='Name of the target product')
parser.add_argument('--root', type=str, default="components/meshx", help='Root directory path for MeshX')
parser.add_argument('--config', type=str, default=".", help='directory to generate meshx_config.h')
parser.add_argument('--profile', type=str, default="tools/scripts", help='directory to get product_profile.yml')
parser.add_argument('--max-size', type=int, default=4096, help='Maximum size allowed for the binary config (bytes)')

# Header block for autogenerated code
file_insert =   "/****************************************************************************\n"\
                " * MESHX AUTOGEN CODE \n"\
                " * @brief This file is auto-generated by the meshx tool. \n"\
                " *       Do not modify this file manually.\n"\
                " *\n"\
                " * @file meshx_config.h\n"\
                " *\n"\
                " ****************************************************************************/\n"\
                "#ifndef __MESHX_AUTO_GEN__\n#define __MESHX_AUTO_GEN__\n"

# Custom exception class for CodeGen
class CodeGenException(Exception):
    """
    Custom exception class for CodeGen.
    """
    pass

class CodeGen(CodeGenException):
    """
    CodeGen class for generating code from product and model profiles.
    """
    def __init__(self,
                 target_name,
                 meshx_root,
                 config_path="components/meshx/default/inc",
                 prod_profile="tools/scripts/prod_profile.yml",
                 model_profile="tools/scripts/model_profile.yml"
            ):
        """
        Initialize the CodeGen class with product and model profiles in YAML format.

        Args:
            target_name (str): Name of the target product.
            prod_profile (str): Path to the product profile YAML file.
            model_profile (str): Path to the model profile YAML file.
        """
        self.max_el = 1
        self.target = target_name
        self.meshx_root = meshx_root
        # Load product and model profiles from YAML files
        with open(prod_profile) as pj:
            self.prod_profile = yaml.safe_load(pj)
        with open(model_profile) as mj:
            self.prod_profile.update(yaml.safe_load(mj))
        self.product_list = []
        self.product = None
        self.pid = None
        self.cid = self.prod_profile['prod']['cid']
        self.c_list = []  # List of source files
        self.inc_list = []  # List of include directories
        self.deps = {}  # Dependency dictionary
        self.__find_prod_from_target()
        self.file_insert = file_insert
        self.genfile_h = config_path + "/meshx_config.h" #self.meshx_root + "/default/inc/meshx_config.h"
        self.genfile_bin = config_path + "/meshx_cfg.bin"
        self.define_fmt = "\n#define {}{}{}"
        if os.name == 'nt':
            os.system(f'echo.>{self.genfile_h}')  # Create the header file
        elif os.name =='posix':
            os.system(f'touch {self.genfile_h}')  # Create the header file

    def __str__(self):
        """
            Return the autogenerated code as a string.
        """
        return self.file_insert

    def __get_fmt_define(self, name, value):
        """
        Get the define format for the autogenerated code.
        """
        leng = 50 - len(name)
        return self.define_fmt.format(name, (" " * leng), value)

    def __find_prod_from_target(self):
        """
        Find the product from the target name.
        """
        self.product_list = self.prod_profile['prod']['products']
        for product in self.product_list:
            if product['name'] == self.target:
                self.product = product
                self.pid = self.product['pid']
        if self.product is None:
            raise CodeGenException("Product Not Found")

    def __get_src_from_path(self, path):
        """
        Get all source files from the given path.
        """
        if path is None:
            return
        path_walk = self.meshx_root + "/" + path
        for (root,dirs,files) in os.walk(path_walk):
            for file in files:
                if file.endswith('.c'):  # Check if the file ends with .c
                    filepath = f"{root}/{file}"
                    if filepath not in self.c_list:
                        self.c_list.append(filepath)  # Add full path to list
                if file.endswith('.h') and f"{root}" not in self.inc_list:
                    self.inc_list.append(root)

    def __resolve_dep_create_yml_dict(self, dep_s, value:int = 0):
        """
        Resolve dependencies and create a dictionary from the YAML file.
        """
        for _idx, dep in enumerate(self.prod_profile['elements']):
            if dep["name"] == dep_s:
                self.deps[dep_s] = {'path' : dep['path']}
                if isinstance(dep['macro']['value'], bool):
                    self.prod_profile['elements'][_idx]['macro']['value'] = True
                else:
                    self.prod_profile['elements'][_idx]['macro']['value'] = value

                for sub_dep in dep['deps']:
                    self.__resolve_dep_create_yml_dict(sub_dep)

    def close(self):
        """
        Close the CodeGen class and write the autogenerated code to a header file.
        """
        self.get_all_macro()
        self.file_insert += "\n\n#endif /* __MESHX_AUTO_GEN__ */"
        with open(self.genfile_h, 'w') as genfile:
            genfile.write(str(self) + '\n')

    def get_common_defs(self):
        """
        Get common definitions from the product profile.
        """
        self.max_el = 1
        if self.product is not None:
            for element in self.product['elements']:
                values = element.values()
                for value in values:
                    self.max_el += value
        self.file_insert += self.__get_fmt_define("CONFIG_CID_ID", hex(self.cid))
        self.file_insert += self.__get_fmt_define("CONFIG_PID_ID", hex(self.pid))
        self.file_insert += self.__get_fmt_define("CONFIG_PRODUCT_NAME", f'"{self.target[:16:]}"')
        self.file_insert += self.__get_fmt_define("CONFIG_MAX_ELEMENT_COUNT", self.max_el)

        # Parse and generate GPIO configuration if present
        self._generate_element_type_enum()
        self._generate_gpio_config()

        return self.file_insert

    def _generate_element_type_enum(self):
        """
        Generate the meshx_element_type_t enum based on model_profile.yml.
        """
        elements_profile = self.prod_profile.get('elements', {})
        enum_str = "\n/**\n * @brief Auto-generated Element Types\n */\n"
        enum_str += "typedef enum meshx_element_type\n{\n"
        
        for name in elements_profile.keys():
            # Convert name to uppercase and prefix with MESHX_ELEMENT_TYPE_
            enum_name = "MESHX_ELEMENT_TYPE_" + name.upper()
            enum_str += f"    {enum_name},\n"
            
        enum_str += "    MESHX_ELEMENT_TYPE_MAX,\n"
        enum_str += "    MESHX_ELEMENT_TYPE_ALL = 0xFF\n"
        enum_str += "} meshx_element_type_t;\n\n"
        
        self.file_insert += enum_str

    def _generate_gpio_config(self):
        """
        Generate GPIO configuration macros if GPIO is configured in product profile.
        """
        if self.product is None or 'gpio' not in self.product:
            return

        try:
            gpio_config = self.product['gpio']

            # Validate GPIO configuration structure
            if 'pins' not in gpio_config:
                print("Warning: GPIO configuration missing 'pins' section")
                return

            pins = gpio_config['pins']
            if not isinstance(pins, list):
                print("Warning: GPIO pins must be a list")
                return

            # Generate GPIO pin count macro
            pin_count = len(pins)
            self.file_insert += self.__get_fmt_define("CONFIG_GPIO_PIN_COUNT", pin_count)

            # Collect entries for the configuration table
            table_entries = []
            for pin_idx, pin_config in enumerate(pins):
                self._generate_gpio_pin_macros(pin_config, pin_idx)
                entry = self._generate_gpio_pin_table_entry(pin_config)
                table_entries.append(entry)

            # Generate the table initializer macro
            if table_entries:
                table_macro = "\n#define CONFIG_GPIO_PIN_CONFIG_TABLE \\\n    " + ", \\\n    ".join(table_entries)
                self.file_insert += table_macro + "\n"

        except Exception as e:
            print(f"Warning: Error processing GPIO configuration: {e}")

    def _generate_gpio_pin_table_entry(self, pin_config):
        """
        Generate a C structure initializer entry for a GPIO pin.
        """
        mode_map = {
            'input': 0, 'output': 1, 'input_output': 2,
            'open_drain': 3, 'open_drain_input_output': 4, 'pwm_output': 5
        }
        pull_map = {'none': 0, 'pull_up': 1, 'pull_down': 2, 'pull_up_down': 3}
        drive_map = {'weak': 0, 'medium': 1, 'strong': 2, 'max_strong': 3}
        intr_map = {
            'disabled': 0, 'positive_edge': 1, 'negative_edge': 2,
            'any_edge': 3, 'low_level': 4, 'high_level': 5
        }

        mode = mode_map.get(pin_config.get('mode', 'input'), 0)
        pull = pull_map.get(pin_config.get('pull', 'none'), 0)
        drive = drive_map.get(pin_config.get('drive_strength', 'weak'), 0)
        initial_level = pin_config.get('initial_level', 0)
        inversion = 1 if pin_config.get('signal_inversion', False) else 0

        # Mode specific config
        mode_config = "{{0}}"
        if mode == 5: # PWM
            pwm = pin_config.get('pwm', {})
            freq = pwm.get('frequency', 1000)
            duty = pwm.get('duty_cycle', 0)
            res = pwm.get('resolution', 10)
            chan = pwm.get('channel', 0)
            mode_config = f"{{.pwm = {{.frequency = {freq}, .duty_cycle = {duty}, .resolution = {res}, .channel = {chan}}}}}"
        elif 'interrupt' in pin_config:
            intr = pin_config['interrupt']
            trigger = intr_map.get(intr.get('trigger', 'disabled'), 0)
            priority = intr.get('task_priority', 5)
            stack = intr.get('task_stack_size', 2048)
            mode_config = f"{{.interrupt = {{.trigger = {trigger}, .task_priority = {priority}, .task_stack_size = {stack}}}}}"

        entry = (f"{{.logical_pin = {pin_config['logical_pin']}, "
                 f".physical_pin = {pin_config['physical_pin']}, "
                 f".mode = {mode}, .pull = {pull}, .drive_strength = {drive}, "
                 f".initial_level = {initial_level}, .signal_inversion = {inversion}, "
                 f".mode_config = {mode_config}}}")
        return entry

    def _generate_gpio_pin_macros(self, pin_config, pin_idx):
        """
        Generate macros for a single GPIO pin.

        Args:
            pin_config (dict): GPIO pin configuration
            pin_idx (int): Pin index for error reporting
        """
        try:
            # Basic validation
            required_fields = ['name', 'logical_pin', 'physical_pin', 'mode']
            for field in required_fields:
                if field not in pin_config:
                    print(f"Warning: GPIO pin {pin_idx} missing required field: {field}")
                    return

            name = pin_config['name']
            logical_pin = pin_config['logical_pin']
            physical_pin = pin_config['physical_pin']

            # Generate pin definition macros
            self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_LOGICAL", logical_pin)
            self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PHYSICAL", physical_pin)

            # Generate mode macro
            mode_map = {
                'input': 0,
                'output': 1,
                'input_output': 2,
                'open_drain': 3,
                'open_drain_input_output': 4,
                'pwm_output': 5
            }
            mode = pin_config.get('mode', 'input')
            mode_value = mode_map.get(mode, 0)
            self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_MODE", mode_value)

            # Generate pull macro if specified
            if 'pull' in pin_config:
                pull_map = {
                    'none': 0,
                    'pull_up': 1,
                    'pull_down': 2,
                    'pull_up_down': 3
                }
                pull_value = pull_map.get(pin_config['pull'], 0)
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PULL", pull_value)

            # Generate drive strength macro if specified
            if 'drive_strength' in pin_config:
                drive_map = {
                    'weak': 0,
                    'medium': 1,
                    'strong': 2,
                    'max_strong': 3
                }
                drive_value = drive_map.get(pin_config['drive_strength'], 1)
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_DRIVE", drive_value)

            # Generate initial level macro if specified
            if 'initial_level' in pin_config:
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_INITIAL_LEVEL", pin_config['initial_level'])

            # Generate signal inversion macro if specified
            if 'signal_inversion' in pin_config:
                inv_value = 1 if pin_config['signal_inversion'] else 0
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_SIGNAL_INVERSION", inv_value)

            # Generate PWM macros if applicable
            if mode == 'pwm_output' and 'pwm' in pin_config:
                pwm_config = pin_config['pwm']
                if 'frequency' in pwm_config:
                    self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PWM_FREQUENCY", pwm_config['frequency'])
                if 'duty_cycle' in pwm_config:
                    self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PWM_DUTY_CYCLE", pwm_config['duty_cycle'])
                if 'resolution' in pwm_config:
                    self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PWM_RESOLUTION", pwm_config['resolution'])
                if 'channel' in pwm_config:
                    self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_PWM_CHANNEL", pwm_config['channel'])

            # Generate interrupt macros if applicable
            if 'interrupt' in pin_config:
                intr_config = pin_config['interrupt']
                trigger_map = {
                    'disabled': 0,
                    'positive_edge': 1,
                    'negative_edge': 2,
                    'any_edge': 3,
                    'low_level': 4,
                    'high_level': 5
                }
                trigger = intr_config.get('trigger', 'disabled')
                trigger_value = trigger_map.get(trigger, 0)
                self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_INTR_TRIGGER", trigger_value)

                if 'task_priority' in intr_config:
                    self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_INTR_PRIORITY", intr_config['task_priority'])

                if 'task_stack_size' in intr_config:
                    self.file_insert += self.__get_fmt_define(f"CONFIG_GPIO_{name}_INTR_STACK_SIZE", intr_config['task_stack_size'])

        except Exception as e:
            print(f"Warning: Error generating macros for GPIO pin {pin_idx}: {e}")

    def resolve_component_deps(self, component, value=0):
        """
        Resolve component dependencies and their dependencies.
        """
        if self.product is not None:
            comp_ptr = self.prod_profile['components'][component]
            comp_ptr['macros'][0]['value'] = value
            self.__get_src_from_path(comp_ptr['path'])
            for macro in comp_ptr['macros']:
                macro['value'] = value

    def resolve_base_models_deps(self, base_model):
        """
        Resolve base model dependencies and their dependencies.
        """
        res_base_model = self.prod_profile['base_models'][base_model]
        self.__get_src_from_path(res_base_model['path'])
        for macro in res_base_model['macros']:
            macro['value'] = True

    def resolve_default_models(self):
        """
        Resolve default models and their dependencies.
        """
        for model in self.prod_profile['models']:
            mod = self.prod_profile['models'][model]
            if mod['default']:
                self.__get_src_from_path(mod['path'])
                self.resolve_model_deps(model, 1)

    def resolve_default_components(self):
        """
        Resolve default components and their dependencies.
        """
        for comp in self.prod_profile['components']:
            com = self.prod_profile['components'][comp]
            if com['default']:
                com['macros'][0]['value'] = True
                self.__get_src_from_path(com['path'])

    def resolve_model_deps(self, model, val):
        """
        Resolve model dependencies and their dependencies.
        """
        res_model = self.prod_profile['models'][model]
        self.__get_src_from_path(res_model['path'])
        for macro in res_model['macros']:
            if isinstance(macro['value'], bool):
                macro['value'] = True
            else:
                macro['value'] += val
        if res_model['base_model'] is not None:
            self.resolve_base_models_deps(res_model['base_model'])

    def resolve_el_deps(self, element, value=0):
        """
        Resolve element dependencies and their dependencies.
        """
        if self.product is not None:
            element_ptr = self.prod_profile['elements'][element]
            element_ptr['macros'][0]['value'] = value
            self.__get_src_from_path(element_ptr['path'])
            for model_reg in element_ptr['models']:
                for model_key, model_val in model_reg.items():
                    self.resolve_model_deps(model_key, (model_val * value))

    def resolve_prod_el(self):
        """
        Resolve product elements and their dependencies.
        """
        if self.product is not None:
            for element in self.product['elements']:
                self.resolve_el_deps(list(element.keys())[0], list(element.values())[0])
            try:
                for component in self.product['components']:
                    self.resolve_component_deps(list(component.keys())[0], list(component.values())[0])
            except KeyError:
                pass

    def get_all_macro(self):
        """
        Get all macros from the product profile.
        """
        if self.product is not None:
            for _key in ['elements', 'models', 'base_models', 'components']:
                for __key in self.prod_profile[_key]:
                    for macro in self.prod_profile[_key][__key]['macros']:
                        self.file_insert += self.__get_fmt_define(macro['def'], int(macro['value']))

    def create_cmake_list(self):
        """
        Create a CMake list of source files and include directories.
        """
        self.c_list     = [entry.replace(self.meshx_root + "/", "") for entry in self.c_list]
        self.inc_list   = [entry.replace(self.meshx_root + "/", "") for entry in self.inc_list]
        cmake_c_list_str = [f'    "{x}"' for x in self.c_list]
        cmake_h_list_str = [f'    "{x}"' for x in self.inc_list]
        cmake_src_list = f"set(DEP_SRC \n{'\n'.join(cmake_c_list_str)} \n)"
        cmake_inc_list = f"set(DEP_INC \n{'\n'.join(cmake_h_list_str)} \n)"
        return cmake_src_list, cmake_inc_list

    def generate_binary(self, max_size=4096):
        """
        Generate the meshx_cfg.bin serialized configuration file using Protocol Buffers.
        """
        if meshx_config_pb2 is None:
            print("Error: Protocol Buffers module 'meshx_config_pb2' is not available. Binary generation skipped.")
            return

        config = meshx_config_pb2.MeshXConfig()

        # Type 0x01: Product Identification
        if self.product is not None:
            config.product.cid = self.cid
            config.product.pid = self.pid
            config.product.name = self.target[:32]

        # Type 0x02: Element Composition
        if self.product is not None and 'elements' in self.product:
            # Dynamically generate element type map from model profile indices
            elements_profile = self.prod_profile.get('elements', {})
            element_type_map = {name: idx for idx, name in enumerate(elements_profile.keys())}

            el_list = self.product['elements']
            for el_entry in el_list:
                for el_name, el_count in el_entry.items():
                    if el_name in element_type_map:
                        el_msg = config.elements.add()
                        el_msg.type = element_type_map[el_name]
                        el_msg.count = el_count

        # Type 0x03 & 0x05: GPIO and Binding
        if self.product is not None and 'gpio' in self.product:
            # GPIO Configuration
            pins = self.product['gpio'].get('pins', [])
            for p in pins:
                pin_msg = config.gpio.add()
                pin_msg.logical_pin = p.get('logical_pin', 0)
                pin_msg.physical_pin = p.get('physical_pin', 0)

            # Element-IO Binding
            bindings = self.product['gpio'].get('bindings', [])
            for b in bindings:
                bind_msg = config.bindings.add()
                bind_msg.element_id = b.get('element_id', 0)
                bind_msg.logical_pin = b.get('logical_pin', 0)
                bind_msg.usage = b.get('usage', 0)

        # Serialize Protobuf payload
        payload = config.SerializeToString()

        # Header Generation
        magic = 0x4D58
        version = 0x01
        total_len = 9 + len(payload)

        header_no_crc = struct.pack('<HBH', magic, version, total_len)
        header_crc = crc16_ccitt(header_no_crc)
        payload_crc = crc16_ccitt(payload)

        header = header_no_crc + struct.pack('<HH', header_crc, payload_crc)

        full_bin = header + payload

        # Size Validation
        if len(full_bin) > max_size:
            raise CodeGenException(f"Error: Generated binary size ({len(full_bin)} bytes) exceeds the limit of {max_size} bytes!")

        with open(self.genfile_bin, 'wb') as f:
            f.write(full_bin)
        print(f"Generated binary config: {self.genfile_bin} ({len(full_bin)} bytes)")

if __name__ == '__main__':
    args = parser.parse_args()
    gen = CodeGen(args.prod, args.root, config_path = args.config, prod_profile = args.profile )
    gen.get_common_defs()
    gen.resolve_default_components()
    gen.resolve_prod_el()
    gen.resolve_default_models()
    gen.close()
    gen.generate_binary(max_size=args.max_size)

    print(f">> Autogen code created! \n{gen}")
