/**
 * @file gpio_pin_map.c
 * @brief GPIO Pin Mapping Implementation for ESP32 WROOM DevKit BSP
 */

#include "gpio_pin_map.h"
#include <stddef.h>

/**
 * @brief ESP32 WROOM DevKit physical to logical pin mapping
 *
 * Note: Not all ESP32 GPIOs are available on the DevKit
 */
const uint8_t esp32_devkitc_physical_to_logical[] = {
    [0]  = ESP32_DEVKITC_PIN_GPIO0,
    [1]  = ESP32_DEVKITC_PIN_GPIO1,
    [2]  = ESP32_DEVKITC_PIN_GPIO2,
    [3]  = ESP32_DEVKITC_PIN_GPIO3,
    [4]  = ESP32_DEVKITC_PIN_GPIO4,
    [5]  = ESP32_DEVKITC_PIN_GPIO5,
    [6]  = ESP32_DEVKITC_PIN_GPIO6,
    [7]  = ESP32_DEVKITC_PIN_GPIO7,
    [8]  = ESP32_DEVKITC_PIN_GPIO8,
    [9]  = ESP32_DEVKITC_PIN_GPIO9,
    [10] = ESP32_DEVKITC_PIN_GPIO10,
    [11] = ESP32_DEVKITC_PIN_GPIO11,
    [12] = ESP32_DEVKITC_PIN_GPIO12,
    [13] = ESP32_DEVKITC_PIN_GPIO13,
    [14] = ESP32_DEVKITC_PIN_GPIO14,
    [15] = ESP32_DEVKITC_PIN_GPIO15,
    [16] = ESP32_DEVKITC_PIN_GPIO16,
    [17] = ESP32_DEVKITC_PIN_GPIO17,
    [18] = ESP32_DEVKITC_PIN_GPIO18,
    [19] = ESP32_DEVKITC_PIN_GPIO19,
    [21] = ESP32_DEVKITC_PIN_GPIO21,
    [22] = ESP32_DEVKITC_PIN_GPIO22,
    [23] = ESP32_DEVKITC_PIN_GPIO23,
    [25] = ESP32_DEVKITC_PIN_GPIO25,
    [26] = ESP32_DEVKITC_PIN_GPIO26,
    [27] = ESP32_DEVKITC_PIN_GPIO27,
    [32] = ESP32_DEVKITC_PIN_GPIO32,
    [33] = ESP32_DEVKITC_PIN_GPIO33,
    [34] = ESP32_DEVKITC_PIN_GPIO34,
    [35] = ESP32_DEVKITC_PIN_GPIO35,
    [36] = ESP32_DEVKITC_PIN_GPIO36,
    [37] = ESP32_DEVKITC_PIN_GPIO37,
    [38] = ESP32_DEVKITC_PIN_GPIO38,
    [39] = ESP32_DEVKITC_PIN_GPIO39,
};

/**
 * @brief ESP32 WROOM DevKit logical to physical pin mapping
 */
const uint8_t esp32_devkitc_logical_to_physical[] = {
    [ESP32_DEVKITC_PIN_GPIO0]  = 0,
    [ESP32_DEVKITC_PIN_GPIO1]  = 1,
    [ESP32_DEVKITC_PIN_GPIO2]  = 2,
    [ESP32_DEVKITC_PIN_GPIO3]  = 3,
    [ESP32_DEVKITC_PIN_GPIO4]  = 4,
    [ESP32_DEVKITC_PIN_GPIO5]  = 5,
    [ESP32_DEVKITC_PIN_GPIO6]  = 6,
    [ESP32_DEVKITC_PIN_GPIO7]  = 7,
    [ESP32_DEVKITC_PIN_GPIO8]  = 8,
    [ESP32_DEVKITC_PIN_GPIO9]  = 9,
    [ESP32_DEVKITC_PIN_GPIO10] = 10,
    [ESP32_DEVKITC_PIN_GPIO11] = 11,
    [ESP32_DEVKITC_PIN_GPIO12] = 12,
    [ESP32_DEVKITC_PIN_GPIO13] = 13,
    [ESP32_DEVKITC_PIN_GPIO14] = 14,
    [ESP32_DEVKITC_PIN_GPIO15] = 15,
    [ESP32_DEVKITC_PIN_GPIO16] = 16,
    [ESP32_DEVKITC_PIN_GPIO17] = 17,
    [ESP32_DEVKITC_PIN_GPIO18] = 18,
    [ESP32_DEVKITC_PIN_GPIO19] = 19,
    [ESP32_DEVKITC_PIN_GPIO21] = 21,
    [ESP32_DEVKITC_PIN_GPIO22] = 22,
    [ESP32_DEVKITC_PIN_GPIO23] = 23,
    [ESP32_DEVKITC_PIN_GPIO25] = 25,
    [ESP32_DEVKITC_PIN_GPIO26] = 26,
    [ESP32_DEVKITC_PIN_GPIO27] = 27,
    [ESP32_DEVKITC_PIN_GPIO32] = 32,
    [ESP32_DEVKITC_PIN_GPIO33] = 33,
    [ESP32_DEVKITC_PIN_GPIO34] = 34,
    [ESP32_DEVKITC_PIN_GPIO35] = 35,
    [ESP32_DEVKITC_PIN_GPIO36] = 36,
    [ESP32_DEVKITC_PIN_GPIO37] = 37,
    [ESP32_DEVKITC_PIN_GPIO38] = 38,
    [ESP32_DEVKITC_PIN_GPIO39] = 39,
};

/**
 * @brief ESP32 WROOM DevKit pin names as strings
 */
const char* esp32_devkitc_pin_names[] = {
    [ESP32_DEVKITC_PIN_GPIO0]  = "GPIO0",
    [ESP32_DEVKITC_PIN_GPIO1]  = "GPIO1",
    [ESP32_DEVKITC_PIN_GPIO2]  = "GPIO2",
    [ESP32_DEVKITC_PIN_GPIO3]  = "GPIO3",
    [ESP32_DEVKITC_PIN_GPIO4]  = "GPIO4",
    [ESP32_DEVKITC_PIN_GPIO5]  = "GPIO5",
    [ESP32_DEVKITC_PIN_GPIO6]  = "GPIO6",
    [ESP32_DEVKITC_PIN_GPIO7]  = "GPIO7",
    [ESP32_DEVKITC_PIN_GPIO8]  = "GPIO8",
    [ESP32_DEVKITC_PIN_GPIO9]  = "GPIO9",
    [ESP32_DEVKITC_PIN_GPIO10] = "GPIO10",
    [ESP32_DEVKITC_PIN_GPIO11] = "GPIO11",
    [ESP32_DEVKITC_PIN_GPIO12] = "GPIO12",
    [ESP32_DEVKITC_PIN_GPIO13] = "GPIO13",
    [ESP32_DEVKITC_PIN_GPIO14] = "GPIO14",
    [ESP32_DEVKITC_PIN_GPIO15] = "GPIO15",
    [ESP32_DEVKITC_PIN_GPIO16] = "GPIO16",
    [ESP32_DEVKITC_PIN_GPIO17] = "GPIO17",
    [ESP32_DEVKITC_PIN_GPIO18] = "GPIO18",
    [ESP32_DEVKITC_PIN_GPIO19] = "GPIO19",
    [ESP32_DEVKITC_PIN_GPIO21] = "GPIO21",
    [ESP32_DEVKITC_PIN_GPIO22] = "GPIO22",
    [ESP32_DEVKITC_PIN_GPIO23] = "GPIO23",
    [ESP32_DEVKITC_PIN_GPIO25] = "GPIO25",
    [ESP32_DEVKITC_PIN_GPIO26] = "GPIO26",
    [ESP32_DEVKITC_PIN_GPIO27] = "GPIO27",
    [ESP32_DEVKITC_PIN_GPIO32] = "GPIO32",
    [ESP32_DEVKITC_PIN_GPIO33] = "GPIO33",
    [ESP32_DEVKITC_PIN_GPIO34] = "GPIO34",
    [ESP32_DEVKITC_PIN_GPIO35] = "GPIO35",
    [ESP32_DEVKITC_PIN_GPIO36] = "GPIO36",
    [ESP32_DEVKITC_PIN_GPIO37] = "GPIO37",
    [ESP32_DEVKITC_PIN_GPIO38] = "GPIO38",
    [ESP32_DEVKITC_PIN_GPIO39] = "GPIO39",
};

/**
 * @brief ESP32 WROOM DevKit pin capabilities
 */
const uint32_t esp32_devkitc_pin_capabilities[] = {
    [ESP32_DEVKITC_PIN_GPIO0]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO1]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO2]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO3]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO4]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO5]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO6]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO7]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO8]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO9]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO10] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO11] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO12] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO13] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO14] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO15] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO16] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO17] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO18] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO19] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO21] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO22] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO23] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO25] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_DAC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO26] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_DAC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO27] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO32] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO33] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO34] = GPIO_CAP_INPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO35] = GPIO_CAP_INPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO36] = GPIO_CAP_INPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO37] = GPIO_CAP_INPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO38] = GPIO_CAP_INPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [ESP32_DEVKITC_PIN_GPIO39] = GPIO_CAP_INPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
};

bool gpio_is_physical_pin_valid(uint8_t physical_pin)
{
    return (physical_pin < sizeof(esp32_devkitc_physical_to_logical) / sizeof(esp32_devkitc_physical_to_logical[0]) &&
            esp32_devkitc_physical_to_logical[physical_pin] != ESP32_DEVKITC_GPIO_PIN_INVALID);
}

bool gpio_is_logical_pin_valid(uint8_t logical_pin)
{
    return (logical_pin < ESP32_DEVKITC_PIN_MAX &&
            esp32_devkitc_logical_to_physical[logical_pin] != ESP32_DEVKITC_GPIO_PIN_INVALID);
}

uint8_t gpio_map_logical_to_physical(uint8_t logical_pin)
{
    if (logical_pin < ESP32_DEVKITC_PIN_MAX) {
        return esp32_devkitc_logical_to_physical[logical_pin];
    }
    return ESP32_DEVKITC_GPIO_PIN_INVALID;
}

uint8_t gpio_map_physical_to_logical(uint8_t physical_pin)
{
    if (physical_pin < sizeof(esp32_devkitc_physical_to_logical) / sizeof(esp32_devkitc_physical_to_logical[0])) {
        return esp32_devkitc_physical_to_logical[physical_pin];
    }
    return ESP32_DEVKITC_GPIO_PIN_INVALID;
}

const char* gpio_get_pin_name(uint8_t logical_pin)
{
    if (logical_pin < ESP32_DEVKITC_PIN_MAX) {
        return esp32_devkitc_pin_names[logical_pin];
    }
    return NULL;
}

uint32_t gpio_get_pin_capabilities(uint8_t physical_pin)
{
    uint8_t logical_pin = gpio_map_physical_to_logical(physical_pin);
    if (logical_pin < ESP32_DEVKITC_PIN_MAX) {
        return esp32_devkitc_pin_capabilities[logical_pin];
    }
    return 0;
}
