/****************************************************************************
 * MESHX AUTOGEN CODE
 * @brief This file is auto-generated by the meshx tool.
 *       Do not modify this file manually.
 *
 * @file meshx_config.h
 *
 ****************************************************************************/
#ifndef __MESHX_AUTO_GEN__
#define __MESHX_AUTO_GEN__

#include "sdkconfig.h"

// #define CONFIG_CID_ID                           0x7908
// #define CONFIG_PID_ID                           0x4
// #define CONFIG_PRODUCT_NAME                     "all_in_one"
// #define CONFIG_MAX_ELEMENT_COUNT                5
// #define CONFIG_RELAY_SERVER_COUNT               1
// #define CONFIG_RELAY_CLIENT_COUNT               1
// #define CONFIG_LIGHT_CWWW_SRV_COUNT             1
// #define CONFIG_LIGHT_CWWW_CLIENT_COUNT          1
// #define CONFIG_ENABLE_SERVER_COMMON             1
// #define CONFIG_ENABLE_PROVISIONING              1
// #define CONFIG_ENABLE_CONFIG_SERVER             1
// #define CONFIG_ENABLE_GEN_ONOFF_CLIENT          1
// #define CONFIG_ENABLE_GEN_ONOFF_SERVER          1
// #define CONFIG_ENABLE_LIGHT_CTL_SERVER          1
// #define CONFIG_ENABLE_LIGHT_HSL_SERVER          0
// #define CONFIG_LIGHT_CTL_CLIENT_COUNT           1
// #define CONFIG_ENABLE_GEN_CLIENT                1
// #define CONFIG_ENABLE_LIGHT_CLIENT              1
// #define CONFIG_ENABLE_GEN_SERVER                1
// #define CONFIG_ENABLE_LIGHT_SERVER              1
// #define CONFIG_MESHX_DEFAULT                    1
// #define CONFIG_ENABLE_UNIT_TEST                 1

#endif /* __MESHX_AUTO_GEN__ */
