var meshx__ble__mesh__gen__cli_8h =
[
    [ "meshx_gen_onoff_set_t", "d1/d7f/structmeshx__gen__onoff__set__t.html", "d1/d7f/structmeshx__gen__onoff__set__t" ],
    [ "meshx_gen_level_set_t", "d5/d5c/structmeshx__gen__level__set__t.html", "d5/d5c/structmeshx__gen__level__set__t" ],
    [ "meshx_gen_delta_set_t", "d3/d81/structmeshx__gen__delta__set__t.html", "d3/d81/structmeshx__gen__delta__set__t" ],
    [ "meshx_gen_move_set_t", "dc/dd5/structmeshx__gen__move__set__t.html", "dc/dd5/structmeshx__gen__move__set__t" ],
    [ "meshx_gen_def_trans_time_set_t", "db/d6e/structmeshx__gen__def__trans__time__set__t.html", "db/d6e/structmeshx__gen__def__trans__time__set__t" ],
    [ "meshx_gen_onpowerup_set_t", "dc/d48/structmeshx__gen__onpowerup__set__t.html", "dc/d48/structmeshx__gen__onpowerup__set__t" ],
    [ "meshx_gen_power_level_set_t", "d4/dba/structmeshx__gen__power__level__set__t.html", "d4/dba/structmeshx__gen__power__level__set__t" ],
    [ "meshx_gen_power_default_set_t", "db/db7/structmeshx__gen__power__default__set__t.html", "db/db7/structmeshx__gen__power__default__set__t" ],
    [ "meshx_gen_power_range_set_t", "d8/d58/structmeshx__gen__power__range__set__t.html", "d8/d58/structmeshx__gen__power__range__set__t" ],
    [ "meshx_gen_loc_global_set_t", "d4/dd7/structmeshx__gen__loc__global__set__t.html", "d4/dd7/structmeshx__gen__loc__global__set__t" ],
    [ "meshx_gen_loc_local_set_t", "dd/da3/structmeshx__gen__loc__local__set__t.html", "dd/da3/structmeshx__gen__loc__local__set__t" ],
    [ "meshx_gen_cli_set_t", "d8/df2/unionmeshx__gen__cli__set__t.html", "d8/df2/unionmeshx__gen__cli__set__t" ],
    [ "meshx_gen_onoff_status_cb_t", "d2/df2/structmeshx__gen__onoff__status__cb__t.html", "d2/df2/structmeshx__gen__onoff__status__cb__t" ],
    [ "meshx_gen_level_status_cb_t", "d5/d50/structmeshx__gen__level__status__cb__t.html", "d5/d50/structmeshx__gen__level__status__cb__t" ],
    [ "meshx_gen_def_trans_time_status_cb_t", "d7/d1f/structmeshx__gen__def__trans__time__status__cb__t.html", "d7/d1f/structmeshx__gen__def__trans__time__status__cb__t" ],
    [ "meshx_gen_onpowerup_status_cb_t", "dc/d7e/structmeshx__gen__onpowerup__status__cb__t.html", "dc/d7e/structmeshx__gen__onpowerup__status__cb__t" ],
    [ "meshx_gen_power_level_status_cb_t", "d3/de3/structmeshx__gen__power__level__status__cb__t.html", "d3/de3/structmeshx__gen__power__level__status__cb__t" ],
    [ "meshx_gen_power_last_status_cb_t", "da/d1c/structmeshx__gen__power__last__status__cb__t.html", "da/d1c/structmeshx__gen__power__last__status__cb__t" ],
    [ "meshx_gen_power_default_status_cb_t", "dd/d25/structmeshx__gen__power__default__status__cb__t.html", "dd/d25/structmeshx__gen__power__default__status__cb__t" ],
    [ "meshx_gen_power_range_status_cb_t", "d2/db1/structmeshx__gen__power__range__status__cb__t.html", "d2/db1/structmeshx__gen__power__range__status__cb__t" ],
    [ "meshx_gen_battery_status_cb_t", "d2/d2e/structmeshx__gen__battery__status__cb__t.html", "d2/d2e/structmeshx__gen__battery__status__cb__t" ],
    [ "meshx_gen_loc_global_status_cb_t", "dc/d0a/structmeshx__gen__loc__global__status__cb__t.html", "dc/d0a/structmeshx__gen__loc__global__status__cb__t" ],
    [ "meshx_gen_loc_local_status_cb_t", "d3/d81/structmeshx__gen__loc__local__status__cb__t.html", "d3/d81/structmeshx__gen__loc__local__status__cb__t" ],
    [ "meshx_gen_user_properties_status_cb_t", "d0/d5a/structmeshx__gen__user__properties__status__cb__t.html", "d0/d5a/structmeshx__gen__user__properties__status__cb__t" ],
    [ "meshx_gen_user_property_status_cb_t", "d6/da0/structmeshx__gen__user__property__status__cb__t.html", "d6/da0/structmeshx__gen__user__property__status__cb__t" ],
    [ "meshx_gen_admin_properties_status_cb_t", "da/d1e/structmeshx__gen__admin__properties__status__cb__t.html", "da/d1e/structmeshx__gen__admin__properties__status__cb__t" ],
    [ "meshx_gen_admin_property_status_cb_t", "db/dfb/structmeshx__gen__admin__property__status__cb__t.html", "db/dfb/structmeshx__gen__admin__property__status__cb__t" ],
    [ "meshx_gen_manufacturer_properties_status_cb_t", "d0/d1c/structmeshx__gen__manufacturer__properties__status__cb__t.html", "d0/d1c/structmeshx__gen__manufacturer__properties__status__cb__t" ],
    [ "meshx_gen_manufacturer_property_status_cb_t", "dc/d11/structmeshx__gen__manufacturer__property__status__cb__t.html", "dc/d11/structmeshx__gen__manufacturer__property__status__cb__t" ],
    [ "meshx_gen_client_properties_status_cb_t", "d3/dd9/structmeshx__gen__client__properties__status__cb__t.html", "d3/dd9/structmeshx__gen__client__properties__status__cb__t" ],
    [ "meshx_gen_client_status_cb_t", "d0/d91/unionmeshx__gen__client__status__cb__t.html", "d0/d91/unionmeshx__gen__client__status__cb__t" ],
    [ "meshx_gen_cli_cb_param", "da/d21/structmeshx__gen__cli__cb__param.html", "da/d21/structmeshx__gen__cli__cb__param" ],
    [ "meshx_gen_cli_cb_param_t", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a44274a423ada4a4e52aeb5d83c3e118b", null ],
    [ "meshx_gen_client_cb_t", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a4d6a7887192f0829652a3dc0614ea3d2", null ],
    [ "meshx_gen_cli_evt_t", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a746eef66dd8f3631866a3b3aecdfbc81", [
      [ "MESHX_GEN_CLI_EVT_GET", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a746eef66dd8f3631866a3b3aecdfbc81a63c428ae25815bc13a6020ffe2c0eded", null ],
      [ "MESHX_GEN_CLI_EVT_SET", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a746eef66dd8f3631866a3b3aecdfbc81aad08455e5ad3687a622fc9334615dbbd", null ],
      [ "MESHX_GEN_CLI_PUBLISH", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a746eef66dd8f3631866a3b3aecdfbc81ad9cb2eb508f63251877844626b4e195e", null ],
      [ "MESHX_GEN_CLI_TIMEOUT", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a746eef66dd8f3631866a3b3aecdfbc81af1a2669b0f73b471fc19b69a67a2606f", null ],
      [ "MESHX_GEN_CLI_EVT_ALL", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a746eef66dd8f3631866a3b3aecdfbc81a63aa2682f83c95746c6abe551ce85e74", null ]
    ] ],
    [ "meshx_plat_gen_cli_delete", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a8fe8e5eb7ef98d6f828de07f97ead59d", null ],
    [ "meshx_plat_gen_cli_init", "de/d08/meshx__ble__mesh__gen__cli_8h.html#ab379b0b9bd42e991d46dede2b420d74c", null ],
    [ "meshx_plat_gen_cli_send_msg", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a9a7f82b22f4472ddaca488e202f5bad5", null ],
    [ "meshx_plat_on_off_gen_cli_create", "de/d08/meshx__ble__mesh__gen__cli_8h.html#a9c0eb105e6e14237408cd53f538645da", null ]
];