/**
 * @file meshx_uvp_element.cpp
 * @brief Implementation of Unified MeshX Element for UVP.
 */

#include <variants/meshx_uvp_element.hpp>
#include <meshx_element_registry.hpp>
#include <meshx_api.h>
#include "meshx_config.h"

/**
 * @brief Constructor
 * @param element_idx Element index
 * @param variant Element type
 */
meshXUVPElement::meshXUVPElement(uint16_t element_idx, meshx_element_type_t variant)
    : meshXElementServer(element_idx, 0, 1) // 0 SIG, 1 Vendor
{
    memset(&element_ctx, 0, sizeof(element_ctx));
    element_ctx.pub_addr = MESHX_ADDR_UNASSIGNED;

    /* Restore from NVS if available */
    meshx_nvs_element_ctx_get(element_idx, variant, &element_ctx, sizeof(element_ctx));

    this->register_element_ctx(&element_ctx, sizeof(element_ctx));
    this->set_element_variant(variant);

    /* Determine if client or server based on autogenerated macro and update element_type */
    if (MESHX_ELEMENT_TYPE_IS_CLIENT(variant)) {
        this->set_element_type(meshxElementType_t::MESHX_ELEMENT_TYPE_CLIENT);
    } else {
        this->set_element_type(meshxElementType_t::MESHX_ELEMENT_TYPE_SERVER);
    }
}

/**
 * @brief Get list of supported Vendor models
 * @return Number of Vendor models
 */
uint8_t meshXUVPElement::list_ven_models()
{
    this->get_ven_models().push_back(std::make_unique<meshXUVPModel>(this));
    return 1;
}

/**
 * @brief Get element name
 * @return Element name
 */
const char* meshXUVPElement::get_element_name(void) const
{
    switch(get_element_variant()) {
        case MESHX_ELEMENT_TYPE_RELAY_SERVER: return "UVP Relay Server";
        case MESHX_ELEMENT_TYPE_LIGHT_CWWW_SERVER: return "UVP CWWW Server";
        case MESHX_ELEMENT_TYPE_LIGHT_HSL_SERVER: return "UVP RGB Server";
        case MESHX_ELEMENT_TYPE_SENSOR_SERVER: return "UVP Sensor Server";
        default: return "UVP Generic Element";
    }
}

/**
 * @brief Sync control task message
 * @param evt Event
 */
void meshXUVPElement::sync(control_task_msg_evt_t evt)
{
    MESHX_LOGD(MODULE_ID_BLE_MESH_ELEMENT, "UVP Element [%d] sync: %d", get_element_idx(), evt);
}

/**
 * @brief Handle config task message
 * @param evt Event
 * @param params Parameters
 */
void meshXUVPElement::handle_config(control_task_msg_evt_t evt, const meshx_config_srv_cb_param_t *params)
{
    MESHX_LOGD(MODULE_ID_BLE_MESH_ELEMENT, "UVP Element [%d] config: %d", get_element_idx(), evt);
}

meshx_err_t meshXUVPElement::element_state_change_notify(meshx_ptr_t param, size_t param_size, const meshx_uvp_ctx_t* ctx)
{
    /* Handled only for UVP messages from dispatcher */
    if (!ctx) {
        return MESHX_SUCCESS;
    }

    MESHX_LOGI(MODULE_ID_BLE_MESH_ELEMENT, "UVP Element [%d] state change from 0x%04x (ACK_REQ: %d)",
               get_element_idx(), ctx->src_addr, ctx->ack_req);

    /*
     * Requirement REQ-005: Dual-Response Architecture
     * 1. Unicast ACK to requester (if requested)
     * 2. Publish to Group Address (if valid and requester is different)
     */

    /* Find the UVP model instance */
    auto* uvp_model = static_cast<meshXUVPModel*>(this->get_ven_models()[0].get());
    if (!uvp_model) {
        return MESHX_FAIL;
    }

    /* Logic Step 1: Send Unicast ACK/Status back to the requester */
    if (ctx->ack_req) {
        MESHX_LOGD(MODULE_ID_BLE_MESH_ELEMENT, "UVP Element [%d] sending unicast ACK to 0x%04x",
                   get_element_idx(), ctx->src_addr);
        uvp_model->send(ctx->src_addr,
                        (uint16_t)this->get_element_variant(),
                        param,
                        (uint16_t)param_size,
                        false); // No ACK for ACK
    }

    /* Logic Step 2: Publish updated state to the registered Publish Address */
    if (element_ctx.pub_addr != MESHX_ADDR_UNASSIGNED &&
        element_ctx.pub_addr != ctx->src_addr) {
        MESHX_LOGD(MODULE_ID_BLE_MESH_ELEMENT, "UVP Element [%d] publishing state to 0x%04x",
                   get_element_idx(), element_ctx.pub_addr);
        uvp_model->send(element_ctx.pub_addr,
                        (uint16_t)this->get_element_variant(),
                        param,
                        (uint16_t)param_size,
                        false); // No ACK for publication
    }

    /* Logic Step 3: Send result telemetry to host via MXCP channel */
    MESHX_LOGD(MODULE_ID_BLE_MESH_ELEMENT, "UVP Element [%d] sending telemetry to app",
               get_element_idx());
    meshx_err_t app_err = meshx_send_msg_to_app(
        get_element_idx(),
        (uint16_t)this->get_element_variant(),
        0,
        (uint16_t)param_size,
        param);
    if (app_err != MESHX_SUCCESS) {
        MESHX_LOGE(MODULE_ID_BLE_MESH_ELEMENT, "UVP Element [%d] telemetry send failed: 0x%x",
                   get_element_idx(), app_err);
    }

    return MESHX_SUCCESS;
}


