/**
 * @file gpio_pin_map.c
 * @brief GPIO Pin Mapping Implementation for WeAct ESP32-C3 BSP
 */

#include "gpio_pin_map.h"
#include <stddef.h>

/**
 * @brief WeAct ESP32-C3 physical to logical pin mapping
 */
const uint8_t weact_c3_physical_to_logical[] = {
    [0]  = WEACT_C3_PIN_GPIO0,
    [1]  = WEACT_C3_PIN_GPIO1,
    [2]  = WEACT_C3_PIN_GPIO2,
    [3]  = WEACT_C3_PIN_GPIO3,
    [4]  = WEACT_C3_PIN_GPIO4,
    [5]  = WEACT_C3_PIN_GPIO5,
    [6]  = WEACT_C3_PIN_GPIO6,
    [7]  = WEACT_C3_PIN_GPIO7,
    [8]  = WEACT_C3_PIN_GPIO8,
    [9]  = WEACT_C3_PIN_GPIO9,
    [10] = WEACT_C3_PIN_GPIO10,
    [11] = WEACT_C3_PIN_GPIO11,
    [12] = WEACT_C3_PIN_GPIO12,
    [13] = WEACT_C3_PIN_GPIO13,
    [14] = WEACT_C3_PIN_GPIO14,
    [15] = WEACT_C3_PIN_GPIO15,
    [16] = WEACT_C3_PIN_GPIO16,
    [17] = WEACT_C3_PIN_GPIO17,
    [18] = WEACT_C3_PIN_GPIO18,
    [19] = WEACT_C3_PIN_GPIO19,
    [20] = WEACT_C3_PIN_GPIO20,
    [21] = WEACT_C3_PIN_GPIO21,
};

/**
 * @brief WeAct ESP32-C3 logical to physical pin mapping
 */
const uint8_t weact_c3_logical_to_physical[] = {
    [WEACT_C3_PIN_GPIO0]  = 0,
    [WEACT_C3_PIN_GPIO1]  = 1,
    [WEACT_C3_PIN_GPIO2]  = 2,
    [WEACT_C3_PIN_GPIO3]  = 3,
    [WEACT_C3_PIN_GPIO4]  = 4,
    [WEACT_C3_PIN_GPIO5]  = 5,
    [WEACT_C3_PIN_GPIO6]  = 6,
    [WEACT_C3_PIN_GPIO7]  = 7,
    [WEACT_C3_PIN_GPIO8]  = 8,
    [WEACT_C3_PIN_GPIO9]  = 9,
    [WEACT_C3_PIN_GPIO10] = 10,
    [WEACT_C3_PIN_GPIO11] = 11,
    [WEACT_C3_PIN_GPIO12] = 12,
    [WEACT_C3_PIN_GPIO13] = 13,
    [WEACT_C3_PIN_GPIO14] = 14,
    [WEACT_C3_PIN_GPIO15] = 15,
    [WEACT_C3_PIN_GPIO16] = 16,
    [WEACT_C3_PIN_GPIO17] = 17,
    [WEACT_C3_PIN_GPIO18] = 18,
    [WEACT_C3_PIN_GPIO19] = 19,
    [WEACT_C3_PIN_GPIO20] = 20,
    [WEACT_C3_PIN_GPIO21] = 21,
};

/**
 * @brief WeAct ESP32-C3 pin names as strings
 */
const char* weact_c3_pin_names[] = {
    [WEACT_C3_PIN_GPIO0]  = "GPIO0",
    [WEACT_C3_PIN_GPIO1]  = "GPIO1",
    [WEACT_C3_PIN_GPIO2]  = "GPIO2",
    [WEACT_C3_PIN_GPIO3]  = "GPIO3",
    [WEACT_C3_PIN_GPIO4]  = "GPIO4",
    [WEACT_C3_PIN_GPIO5]  = "GPIO5",
    [WEACT_C3_PIN_GPIO6]  = "GPIO6",
    [WEACT_C3_PIN_GPIO7]  = "GPIO7",
    [WEACT_C3_PIN_GPIO8]  = "GPIO8",
    [WEACT_C3_PIN_GPIO9]  = "GPIO9",
    [WEACT_C3_PIN_GPIO10] = "GPIO10",
    [WEACT_C3_PIN_GPIO11] = "GPIO11",
    [WEACT_C3_PIN_GPIO12] = "GPIO12",
    [WEACT_C3_PIN_GPIO13] = "GPIO13",
    [WEACT_C3_PIN_GPIO14] = "GPIO14",
    [WEACT_C3_PIN_GPIO15] = "GPIO15",
    [WEACT_C3_PIN_GPIO16] = "GPIO16",
    [WEACT_C3_PIN_GPIO17] = "GPIO17",
    [WEACT_C3_PIN_GPIO18] = "GPIO18",
    [WEACT_C3_PIN_GPIO19] = "GPIO19",
    [WEACT_C3_PIN_GPIO20] = "GPIO20",
    [WEACT_C3_PIN_GPIO21] = "GPIO21",
};

/**
 * @brief WeAct ESP32-C3 pin capabilities
 */
const uint32_t weact_c3_pin_capabilities[] = {
    [WEACT_C3_PIN_GPIO0]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO1]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO2]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO3]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO4]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO5]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO6]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO7]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO8]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO9]  = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO10] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO11] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO12] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO13] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO14] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO15] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO16] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO17] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO18] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO19] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO20] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
    [WEACT_C3_PIN_GPIO21] = GPIO_CAP_INPUT | GPIO_CAP_OUTPUT | GPIO_CAP_PULL_UP | GPIO_CAP_PULL_DOWN | GPIO_CAP_OPEN_DRAIN | GPIO_CAP_PWM | GPIO_CAP_ADC | GPIO_CAP_INTERRUPT,
};

bool gpio_is_physical_pin_valid(uint8_t physical_pin)
{
    return (physical_pin < sizeof(weact_c3_physical_to_logical) / sizeof(weact_c3_physical_to_logical[0]) &&
            weact_c3_physical_to_logical[physical_pin] != WEACT_C3_GPIO_PIN_INVALID);
}

bool gpio_is_logical_pin_valid(uint8_t logical_pin)
{
    return (logical_pin < WEACT_C3_PIN_MAX &&
            weact_c3_logical_to_physical[logical_pin] != WEACT_C3_GPIO_PIN_INVALID);
}

uint8_t gpio_map_logical_to_physical(uint8_t logical_pin)
{
    if (logical_pin < WEACT_C3_PIN_MAX) {
        return weact_c3_logical_to_physical[logical_pin];
    }
    return WEACT_C3_GPIO_PIN_INVALID;
}

uint8_t gpio_map_physical_to_logical(uint8_t physical_pin)
{
    if (physical_pin < sizeof(weact_c3_physical_to_logical) / sizeof(weact_c3_physical_to_logical[0])) {
        return weact_c3_physical_to_logical[physical_pin];
    }
    return WEACT_C3_GPIO_PIN_INVALID;
}

const char* gpio_get_pin_name(uint8_t logical_pin)
{
    if (logical_pin < WEACT_C3_PIN_MAX) {
        return weact_c3_pin_names[logical_pin];
    }
    return NULL;
}

uint32_t gpio_get_pin_capabilities(uint8_t physical_pin)
{
    uint8_t logical_pin = gpio_map_physical_to_logical(physical_pin);
    if (logical_pin < WEACT_C3_PIN_MAX) {
        return weact_c3_pin_capabilities[logical_pin];
    }
    return 0;
}
