name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Build all products
      run: |
        cd app
        export APP_PATH=$(pwd)
        sudo docker run --rm -v $PWD:$APP_PATH -w $APP_PATH -u $UID -e HOME=/tmp espressif/idf:release-v5.4 idf.py -DTARGET="all_in_one" set-target esp32c3

        for product in $(python -c "import yaml; print(' '.join([p['name'] for p in yaml.safe_load(open('scripts/prod_profile.yml'))['prod']['products']]))"); do
          sh scripts/build_ci.sh $product
        done
      shell: bash
